runtime: python27
api_version: 1
threadsafe: true
libraries:
  - name: flask
    version: 0.12
  - name: ssl
    version: latest

handlers:
  - url: /admin/.*
    script: admin.app
    login: required
  - url: /.*
    script: main.app
