steps:
- name: 'python'
  args: ['pip', 'install',  '-r', 'requirements.txt', '-t', 'lib']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'index.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
