#!/bin/sh
docker run --rm -p 8080:8080 -e PORT=8080 -e GOOGLE_APPLICATION_CREDENTIALS=/config -e OAUTH_CLIENTID -e OAUTH_CLIENTSECRET -e GOOGLE_CLOUD_PROJECT -e OAUTH_CALLBACK -v $GOOGLE_APPLICATION_CREDENTIALS:/config links
