#!/bin/sh
docker run -p 8080:8080 -e PORT=8080 -e GOOGLE_APPLICATION_CREDENTIALS=/config -e LOCALDB=1 -e OAUTH_CLIENTID -e OAUTH_CLIENTSECRET -e GOOGLE_CLOUD_PROJECT -v $GOOGLE_APPLICATION_CREDENTIALS:/config links
